[package]
name = "blaseball-before"
version = "0.1.0"
authors = ["iliana etaoin <iliana@buttslol.net>"]
edition = "2018"
publish = false

[dependencies]
derive_builder = "0.10"
either = "1"
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.7"

[dependencies.anyhow]
version = "1"
features = ["backtrace"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "serde", "std"]

[dependencies.reqwest]
version = "0.11"
features = ["json", "stream"]

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.5-pre"
features = ["json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio-util]
version = "0.6"
features = ["compat"]
